# Generated by Django 3.1.2 on 2020-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
